sec/local/urls.py
/home/qiuye/SEC/sec/urls.py

sec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),

]

core/models.py
from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

import os
import uuid

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

# Team choices
INDUSTRY = (
     (0, 'None'),
     (1, 'IT'),
     (2, 'Finance'),
     (3, 'Hardware'),
     (4, 'Bio'),
     (5, 'Others'),
    )

TEAM_STATUS = (
     (0, 'None'),
     (1, 'MVP - SEEKING ANGEL'),
     (2, 'SEEKING - A Round'),
     (3, 'SEEKING - B Round'),
     (4, 'Others'),
    )


class Team(models.Model):
    title = models.CharField(max_length=300) # Team Name
    project_status = models.IntegerField(choices=TEAM_STATUS, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname="team_list", args=[self.id])

    def get_users(self):
        return self.profile_set.all()


class Profile(models.Model):
    members = models.ForeignKey(Team, null=True, blank=True)
    user = models.OneToOneField(User)
    # Basic Info both required
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    # Experience & Skills    
    # Need to investigate how to make as multiple choices as Linkedin
    company = models.CharField(max_length=100, blank= True)
    skills = models.CharField(max_length=100, blank= True)

    industry = models.IntegerField(choices=INDUSTRY, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse(viewname="profile_list", args=[self.id])

templates/profile/detail.html
{% extends "base/theme.html" %}
	{% block main_content %}
	<div class="row main-content">
 		<div class="col-md-2"></div>
	    <div class="container">
	      <div class="page-header">
	        <h3>Basic Info:</h3>
	      </div>
	      <p>Name: {{ profile.name}}</p>
	      <p>Email: {{ profile.email}}</p>
	    </div>

	    <div class="container">
	      <div class="page-header">
	      <h3>Experience & Skills:</h3>
            <p>Industry: {% if profile.industry %}
              {{ profile.get_industry_display }}
            {% else %} ----
              {% endif %}</p>
            <p>Company: {% if profile.company %}
              {{ profile.company }}
            {% else %} ----
              {% endif %}</p>
            <p>Skills: {% if profile.skills %}
              {{ profile.skills }}
            {% else %} ----
              {% endif %}</p>
            <p>Introduction: {% if profile.description %}
              {{ profile.description }}
            {% else %} ----
              {% endif %}</p>
	      </div>
	    </div>
        {% if profile.image_file %}
	    <div class="container">
	      <div class="page-header">
              <img class="img-responsive" src="{{ profile.image_file.url }}"></img>
	      </div>
	    </div>
        {% endif %}

	    <div class="container">
		    <p><a type="button" href="{% url 'profile_update' pk=profile.id %}" class="btn btn-primary">Edit Profile Page &raquo;</a></p>
	    </div>

	</div>
{% endblock %}

templates/profile/list.html
{% extends "base/theme.html" %}
{% load bootstrap_pagination %}

{% block main_content %}
  <div class="row main-content">
    <div class="col-md-2"></div>
    <div class='row'>
        <div class="col-md-8">
        {% for profile in object_list %}
         <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><a href="{{ profile.get_absolute_url }}">{{ profile.user.username }}</a></h3>
          </div>
          <div class="panel-body">
            <p><b>User Status: </b>
            {% if profile.industry %}
              {{ profile.get_industry_display }}
            {% else %}----
            {% endif %}</p>

             <p><b>Description: </b>{{ profile.description }}</p>
            <p><b>TEAM: </b>
            {% if profile.members %}
                <a href="/team/{{ profile.members.id }}/detail">{{ profile.members.title }}</a>
            {% else %}----
            {% endif %}</p>
          </div>    
          </div>
         {% endfor %}
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}
{% block pagination %}
 {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}