sec/local/urls.py
/home/qiuye/SEC/sec/urls.py

sec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),

]

core/models.py
from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

import os
import uuid

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

# Team choices
INDUSTRY = (
     (0, 'None'),
     (1, 'IT'),
     (2, 'Finance'),
     (3, 'Hardware'),
     (4, 'Bio'),
     (5, 'Others'),
    )

TEAM_STATUS = (
     (0, 'None'),
     (1, 'MVP - SEEKING ANGEL'),
     (2, 'SEEKING - A Round'),
     (3, 'SEEKING - B Round'),
     (4, 'Others'),
    )


class Team(models.Model):
    title = models.CharField(max_length=300) # Team Name
    project_status = models.IntegerField(choices=TEAM_STATUS, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname="team_list", args=[self.id])

    def get_users(self):
        return self.profile_set.all()


class Profile(models.Model):
    members = models.ForeignKey(Team, null=True, blank=True)
    user = models.OneToOneField(User)
    # Basic Info both required
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    # Experience & Skills    
    # Need to investigate how to make as multiple choices as Linkedin
    company = models.CharField(max_length=100, blank= True)
    skills = models.CharField(max_length=100, blank= True)

    industry = models.IntegerField(choices=INDUSTRY, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse(viewname="profile_list", args=[self.id])

templates/team/detail.html
{% extends "base/theme.html" %}
	{% block main_content %}
	<div class="row main-content">
 		<div class="col-md-2"></div>
	    <div class="container">
	      <div class="page-header">
	        <h3>Team Information:</h3>
	      </div>
	      <p>Name: {{ team.title}}</p>
            {% if team.get_users %}<p>
              <b>Members:
              </b>
              {% for profile in team.get_users %}
              <br>
                <a href="/profile/{{ profile.id }}/detail">{{ profile.user.username }}</a>
             {% endfor %}
            {% endif %}

            <p>Industry: {% if team.project_status %}
              {{ profile.get_project_status_display }}
            {% else %} ----
              {% endif %}</p>
            <p>Description: {% if team.description %}
              {{ team.description }}
            {% else %} ----
              {% endif %}</p>
	      </div>
	    </div>

        {% if team.image_file %}
	    <div class="container">
	      <div class="page-header">
              <img class="img-responsive" src="{{ team.image_file.url }}"></img>
	      </div>
	    </div>
        {% endif %}

	    <div class="container">
		    <p><a type="button" href="{% url 'team_update' pk=team.id %}" class="btn btn-primary">Edit Team Page &raquo;</a></p>
	    </div>
	</div>
{% endblock %}

templates/team/list.html
{% extends "base/theme.html" %}
{% load bootstrap_pagination %}

{% block main_content %}
  <div class="row main-content">
    <div class="col-md-2"></div>
      <div class="col-md-8">
        {% for team in object_list %}
         <div class="panel">
           <h3><a href="{{ team.get_absolute_url }}">{{ team.title }}</a></h3>
            {% if team.status %}<p><b>Status: </b>{{ team.status }}</p>
            {% endif %}
            <p><b>Project Status: </b>
            {% if team.project_status %}
            {{ team.get_project_status_display }}
            {% else %}----
            {% endif %}</p>

            {% if team.get_users %}<p>
              <b>Members:
              </b>
              {% for profile in team.get_users %}
              <br>
                <a href="/profile/{{ profile.user.id }}/detail">{{ profile.user.username }}</a>
             {% endfor %}
            {% endif %}

            {% if team.image_file %}
              <img class="img-responsive" src="{{ team.image_file.url }}"></img>
            {% endif %}
             <p><b>Description: </b>{{ team.description }}</p>
         </div>
         {% endfor %}
      </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}
{% block pagination %}
 {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}